name = "nbeet"
version = "1.1.2"

description = "An NBT encoder and decoder for gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "zwubs", repo = "nbeet" }

[dependencies]
gleam_stdlib = ">= 0.61.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
